name: Deploy Master To enviroment

on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: "Enviroment"
        type: choice
        options:
          - production-emea
          - demo
        required: true

jobs:
  deploy_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out to Branch
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Get current date
        id: date
        run: echo "date_time=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
      - name: Tag RC To Enviroment
        run: |
          git tag ${{ github.event.inputs.enviroment }}_${{ github.actor }}_${{ env.date_time }}
          git push origin ${{ github.event.inputs.enviroment }}_${{ github.actor }}_${{ env.date_time }}
