name: Deploy Release Candidate To Production

on:
  workflow_dispatch:
    inputs:
      release_number:
        description: "Release Number"
        required: true

jobs:
  deploy_master_to_production:
    runs-on: ubuntu-latest

    steps:
      - name: Init git
        with:
          fetch-depth: 0
        uses: actions/checkout@v2
      - name: Find Release Candidate PR Number
        run: |
          echo "pull_request_number=$(gh search prs --base master --label 'release-candidate' --state="open" --limit 1 --json number --jq '.[].number')" >> $GITHUB_ENV
          echo PR Number #${{ env.pull_request_number }}
          echo PR link ${{ github.server_url }}/${{ github.repository }}/pull/${{ env.pull_request_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if PR exists
        if: ${{ env.pull_request_number == '' }}
        run: |
          echo PR does not exists
          exit 1
      - name: Merge Release Candidate to Master
        run: gh pr merge ${{ env.pull_request_number }} -m --delete-branch --admin --body "Merge Release Candidate v${{ env.pull_request_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout out last commit on Master
        with:
          ref: master
          fetch-depth: 0
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "date_time=$(date +'%Y-%m-%d--%H-%M')" >> $GITHUB_ENV
      - name: Tag/Deploy master to production
        run: |
          git tag production_v${{ github.event.inputs.release_number }}_${{ env.date_time }}
          git push origin production_v${{ github.event.inputs.release_number }}_${{ env.date_time }}
      - name: Create Mergeback
        run: gh pr create -B develop --title "Merge Back Release Candidate v${{ github.event.inputs.release_number }}" --body '' --label 'merge-back'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
