name: Deploy Release Candidate With Fix To Pre Prod

on:
  workflow_dispatch:
    inputs:
      release_number:
        description: "Release Number"
        required: true
      build_number:
        description: "Build Number"
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Check out to Branch
        uses: actions/checkout@v2
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Bump Build Version
        run: >
          sed -i 's/"version": ".*",/"version": "2.6",/g' package.json
      - name: Commit new build version
        run: |
          git add package.json
          git commit --message "Bump build version to ${{ github.event.inputs.build_number }}"
      - name: Push updated branch
        run: git push origin
      - name: Tag RC To preprod
        run: |
          git tag preprod_v${{ github.event.inputs.release_number }}_${{ github.event.inputs.build_number }}
          git push origin preprod_v${{ github.event.inputs.release_number }}_${{ github.event.inputs.build_number }}
