name: Create and Deploy Release Candidate

on:
  workflow_dispatch:
    inputs:
      release_number:
        description: "Release Number"
        required: true

jobs:
  checkout_bump_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Develop
        with:
          ref: develop
        uses: actions/checkout@v2
      - name: Create Release Branch
        run: git checkout -b release/v${{ github.event.inputs.release_number }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Push New Branch
        run: git push origin release/v${{ github.event.inputs.release_number }}
      - name: Get current date
        id: date
        run: echo "date_time=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
      - name: Tag/Deploy RC To Preprod
        run: |
          git tag preprod_v${{ github.event.inputs.release_number }}_${{ env.date_time }}
          git push origin preprod_v${{ github.event.inputs.release_number }}_${{ env.date_time }}
      - name: Create RC Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: RC v${{ github.event.inputs.release_number }}
          body: RC v${{ github.event.inputs.release_number }}
          base: master
