name: Create and Deploy Release Candidate

on:
  workflow_dispatch:
    inputs:
      release_number:
        description: "Release Number"
        required: true
      commit_id:
        description: "Commit Id For Cutoff (Last Commit by default)"
        required: false

jobs:
  checkout_deploy_and_create_PR:
    runs-on: ubuntu-latest

    steps:
      - name: Check out last commit on Develop
        with:
          ref: develop
          fetch-depth: 0
        uses: actions/checkout@v2
        if: "${{ github.event.inputs.commit_id == '' }}"
      - name: Check out to commit on Develop
        with:
          ref: ${{ github.event.inputs.commit_id }}
          fetch-depth: 0
        uses: actions/checkout@v2
        if: "${{ github.event.inputs.commit_id != '' }}"
      - name: Create Release Branch
        run: git checkout -b release/v${{ github.event.inputs.release_number }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Push New Branch
        run: git push origin release/v${{ github.event.inputs.release_number }}
      - name: Get current date
        id: date
        run: echo "date_time=$(date +'%Y-%m-%d--%H-%M')" >> $GITHUB_ENV
      - name: Create RC Pull Request
        run: gh pr create -B master -H release/v${{ github.event.inputs.release_number }} --title 'Release Candidate v${{ github.event.inputs.release_number }}' --body '' --label 'release-candidate'
      - name: Tag/Deploy RC To Preprod
        run: |
          git tag preprod_v${{ github.event.inputs.release_number }}_${{ env.date_time }}
          git push origin preprod_v${{ github.event.inputs.release_number }}_${{ env.date_time }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_previous_master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out last commit on Master
        with:
          ref: master
          fetch-depth: 0
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "date_time=$(date +'%Y-%m-%d--%H-%M')" >> $GITHUB_ENV
      - name: Tag/Deploy previous RC To Preprod2
        run: |
          git tag preprod2_v${{ github.event.inputs.release_number }}_${{ env.date_time }}
          git push origin preprod2_v${{ github.event.inputs.release_number }}_${{ env.date_time }}
