name: Deploy Branch To enviroment

on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: "Enviroment"
        type: choice
        options:
          - preprod
          - preprod2
        required: true
jobs:
  deploy_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out to Branch
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "date_time=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
      - name: Tag branch To Enviroment
        run: |
          git tag ${{ github.event.inputs.enviroment }}_${{ github.actor }}_${{ env.date_time }}
          git push origin ${{ github.event.inputs.enviroment }}_${{ github.actor }}_${{ env.date_time }}
