name: Deploy Release Candidate To Production
on: workflow_dispatch

jobs:
  deploy_master_to_production:
    runs-on: ubuntu-latest

    steps:
      - name: Init git
        with:
          fetch-depth: 0
        uses: actions/checkout@v2
      - name: Find Release Candidate PR Number
        run: echo "pull_request_number=$(gh pr list --review 'approved' --base master --label 'release-candidate' --limit 1 --json number --jq '.[].number') | sed -n '1p'" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge Release Candidate to Master
        run: gh pr merge ${{ env.pull_request_number }} -m --delete-branch --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout out last commit on Master
        with:
          ref: master
          fetch-depth: 0
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "date_time=$(date +'%Y-%m-%d--%H-%M')" >> $GITHUB_ENV
      - name: Tag/Deploy master to production
        run: |
          git tag production_v${{ github.event.inputs.release_number }}_${{ env.date_time }}
          git push origin production_v${{ github.event.inputs.release_number }}_${{ env.date_time }}
      - name: Create Mergeback
        run: gh pr create -B develop --title "Merge Back" --body '' --label 'merge-back'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
